import { Iicons } from "@/components/details/comment/comment";
export  const cityOption: any[] = [
    { value: 'Tỉnh thành', label: 'Tỉnh thành' },
    { value: 'Hà Nội', label: 'Hà Nội' },
    { value: 'Hồ Chí Minh', label: 'Hồ Chí Minh' },
    { value: 'Đà Nẵng', label: 'Đà Nẵng' },
    { value: 'Hải Phòng', label: 'Hải Phòng' },
    { value: 'Cần Thơ', label: 'Cần Thơ' },
    { value: 'Bắc Ninh', label: 'Bắc Ninh' },
    { value: 'Hải Dương', label: 'Hải Dương' },
    { value: 'Nam Định', label: 'Nam Định' },
    { value: 'Ninh Bình', label: 'Ninh Bình' },
    { value: 'Thừa Thiên Huế', label: 'Thừa Thiên Huế' },
    { value: 'Quảng Bình', label: 'Quảng Bình' },
    { value: 'Quảng Trị', label: 'Quảng Trị' },
    { value: 'Quảng Ngãi', label: 'Quảng Ngãi' },
    { value: 'Bình Định', label: 'Bình Định' },
    { value: 'Phú Yên', label: 'Phú Yên' },
    { value: 'Khánh Hòa', label: 'Khánh Hòa' },
    { value: 'Gia Lai', label: 'Gia Lai' },
    { value: 'Kon Tum', label: 'Kon Tum' },
    { value: 'Đắk Lắk', label: 'Đắk Lắk' },
    { value: 'Đắk Nông', label: 'Đắk Nông' },
    { value: 'Lâm Đồng', label: 'Lâm Đồng' },
    { value: 'Bình Phước', label: 'Bình Phước' },
    { value: 'Bình Dương', label: 'Bình Dương' },
    { value: 'Đồng Nai', label: 'Đồng Nai' },
    { value: 'Tây Ninh', label: 'Tây Ninh' },
    { value: 'Bà Rịa - Vũng Tàu', label: 'Bà Rịa - Vũng Tàu' },
    { value: 'Long An', label: 'Long An' },
    { value: 'Tiền Giang', label: 'Tiền Giang' },
    { value: 'Bến Tre', label: 'Bến Tre' },
    { value: 'Trà Vinh', label: 'Trà Vinh' },
    { value: 'Vĩnh Long', label: 'Vĩnh Long' },
    { value: 'Đồng Tháp', label: 'Đồng Tháp' },
    { value: 'An Giang', label: 'An Giang' },
    { value: 'Kiên Giang', label: 'Kiên Giang' },
    { value: 'Cà Mau', label: 'Cà Mau' },
    { value: 'Bạc Liêu', label: 'Bạc Liêu' },
    { value: 'Sóc Trăng', label: 'Sóc Trăng' },
    { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
    { value: 'Phú Thọ', label: 'Phú Thọ' },
    { value: 'Bắc Giang', label: 'Bắc Giang' },
    { value: 'Bắc Kạn', label: 'Bắc Kạn' },
    { value: 'Cao Bằng', label: 'Cao Bằng' },
    { value: 'Lạng Sơn', label: 'Lạng Sơn' },
    { value: 'Tuyên Quang', label: 'Tuyên Quang' },
    { value: 'Lào Cai', label: 'Lào Cai' },
    { value: 'Yên Bái', label: 'Yên Bái' },
    { value: 'Sơn La', label: 'Sơn La' },
    { value: 'Hoà Bình', label: 'Hoà Bình' },
    { value: 'Thái Nguyên', label: 'Thái Nguyên' },
    { value: 'Bắc Ninh', label: 'Bắc Ninh' },
    { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
    { value: 'Phú Thọ', label: 'Phú Thọ' },
    { value: 'Bắc Giang', label: 'Bắc Giang' },
    { value: 'Bắc Kạn', label: 'Bắc Kạn' },
    { value: 'Cao Bằng', label: 'Cao Bằng' },
    { value: 'Lạng Sơn', label: 'Lạng Sơn' },
    { value: 'Tuyên Quang', label: 'Tuyên Quang' },
    { value: 'Lào Cai', label: 'Lào Cai' },
    { value: 'Yên Bái', label: 'Yên Bái' },
    { value: 'Sơn La', label: 'Sơn La' },
    { value: 'Hoà Bình', label: 'Hoà Bình' },
    { value: 'Thái Nguyên', label: 'Thái Nguyên' },
    { value: 'Bắc Ninh', label: 'Bắc Ninh' },
    { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
    { value: 'Phú Thọ', label: 'Phú Thọ' },
    { value: 'Bắc Giang', label: 'Bắc Giang' },
    { value: 'Bắc Kạn', label: 'Bắc Kạn' },
    { value: 'Cao Bằng', label: 'Cao Bằng' },
    { value: 'Lạng Sơn', label: 'Lạng Sơn' },
    { value: 'Tuyên Quang', label: 'Tuyên Quang' },
    { value: 'Lào Cai', label: 'Lào Cai' },
    { value: 'Yên Bái', label: 'Yên Bái' },
    { value: 'Sơn La', label: 'Sơn La' },
    { value: 'Hoà Bình', label: 'Hoà Bình' },
    { value: 'Thái Nguyên', label: 'Thái Nguyên' },
    { value: 'Bắc Ninh', label: 'Bắc Ninh' },
    { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
    { value: 'Phú Thọ', label: 'Phú Thọ' },
    { value: 'Bắc Giang', label: 'Bắc Giang' },
    { value: 'Bắc Kạn', label: 'Bắc Kạn' },
    { value: 'Cao Bằng', label: 'Cao Bằng' },
    { value: 'Lạng Sơn', label: 'Lạng Sơn' },
    { value: 'Tuyên Quang', label: 'Tuyên Quang' },
    { value: 'Lào Cai', label: 'Lào Cai' },
    { value: 'Yên Bái', label: 'Yên Bái' },
    { value: 'Sơn La', label: 'Sơn La' },
    { value: 'Hoà Bình', label: 'Hoà Bình' },
    { value: 'Thái Nguyên', label: 'Thái Nguyên' },
    { value: 'Bắc Ninh', label: 'Bắc Ninh' },
    { value: 'Vĩnh Phúc', label: 'Vĩnh Phúc' },
    { value: 'Phú Thọ', label: 'Phú Thọ' },
    { value: 'Bắc Giang', label: 'Bắc Giang' },
    { value: 'Bắc Kạn', label: 'Bắc Kạn' },
    { value: 'Cao Bằng', label: 'Cao Bằng' },
    { value: 'Lạng Sơn', label: 'Lạng Sơn' },
    { value: 'Tuyên Quang', label: 'Tuyên Quang' },
    { value: 'Lào Cai', label: 'Lào Cai' },
    { value: 'Yên Bái', label: 'Yên Bái' },
    { value: 'Sơn La', label: 'Sơn La' },
    { value: 'Hoà Bình', label: 'Hoà Bình' },
    { value: 'Thái Nguyên', label: 'Thái Nguyên' },
    { value: 'Lai Châu', label: 'Lai Châu' },
    { value: 'Điện Biên', label: 'Điện Biên' },
    { value: 'Sơn La', label: 'Sơn La' },
    { value: 'Lào Cai', label: 'Lào Cai' },
    { value: 'Yên Bái', label: 'Yên Bái' },
    { value: 'Hòa Bình', label: 'Hòa Bình' },
  ];
  
export const jobsOptions = [
    { value: 'Ngành nghề', label: 'Ngành nghề' },
    { value: 'Hành chính - Văn phòng', label: 'Hành chính - Văn phòng' },
    { value: 'Kế toàn - Kiểm toán', label: 'Kế toàn - Kiểm toán' },
    { value: 'Nhân viên kinh doanh', label: 'Nhân viên kinh doanh' },
    { value: 'Lao động phổ thông', label: 'Lao động phổ thông' },
    { value: 'Sinh viên làm thêm', label: 'Sinh viên làm thêm' },
    { value: 'Xây dựng', label: 'Xây dựng' },
    { value: 'Vận tải - Lái xe', label: 'Vận tải - Lái xe' },
    { value: 'Việc làm bán hàng', label: 'Việc làm bán hàng' },
    { value: 'Điện - Điện tử', label: 'Điện - Điện tử' },
    { value: 'Y tế - Dược', label: 'Y tế - Dược' },
    { value: 'IT phần mềm', label: 'IT phần mềm' },
    { value: 'Cơ khí - Chế tạo', label: 'Cơ khí - Chế tạo' },
    { value: 'Khách sạn - Nhà hàng', label: 'Khách sạn - Nhà hàng' },
    { value: 'Giáo dục - Đào tạo', label: 'Giáo dục - Đào tạo' },
    { value: 'Việc làm thời vụ', label: 'Việc làm thời vụ' },
    { value: 'Nhân sự', label: 'Nhân sự' },
    { value: 'Kỹ thuật', label: 'Kỹ thuật' },
    { value: 'Biên - Phiên dịch', label: 'Biên - Phiên dịch' },
    { value: 'Xuất - nhập khẩu', label: 'Xuất - nhập khẩu' },
    { value: 'Quản trị kinh doanh', label: 'Quản trị kinh doanh' },
    { value: 'Chăm sóc khách hàng', label: 'Chăm sóc khách hàng' },
    { value: 'Dệt may - Da giày', label: 'Dệt may - Da giày' },
    { value: 'IT Phần cứng - mạng', label: 'IT Phần cứng - mạng' },
    { value: 'Luật - Pháp lý', label: 'Luật - Pháp lý' },
    { value: 'Phục vụ - Tạp vụ', label: 'Phục vụ - Tạp vụ' },
    { value: 'Thẩm định - Giám thẩm định - Quản lý chất lượng', label: 'Thẩm định - Giám thẩm định - Quản lý chất lượng' },
    { value: 'Thực phẩm - Đồ uống', label: 'Thực phẩm - Đồ uống' },
    { value: 'Bảo vệ', label: 'Bảo vệ' },
    { value: 'Dịch vụ', label: 'Dịch vụ' },
    { value: 'Tư vấn', label: 'Tư vấn' },
    { value: 'Sinh viên mới tốt nghiệp - Thực tập', label: 'Sinh viên mới tốt nghiệp - Thực tập' },
    { value: 'Tìm việc làm thêm', label: 'Tìm việc làm thêm' },
    { value: 'Ngân hàng - Chứng khoán - Đầu tư', label: 'Ngân hàng - Chứng khoán - Đầu tư' },
    { value: 'Thiết kế - Mỹ thuật', label: 'Thiết kế - Mỹ thuật' },
    { value: 'Kiến trúc - Tk nội thất', label: 'Kiến trúc - Tk nội thất' },
    { value: 'Quản lý điều hành', label: 'Quản lý điều hành' },
    { value: 'Vận chuyển giao nhận', label: 'Vận chuyển giao nhận' },
    { value: 'Hóa học - Sinh học', label: 'Hóa học - Sinh học' },
    { value: 'Du lịch', label: 'Du lịch' },
    { value: 'Nông - Lâm - Ngư - Nghiệp', label: 'Nông - Lâm - Ngư - Nghiệp' },
    { value: 'Báo chí - Truyền hình', label: 'Báo chí - Truyền hình' },
    { value: 'Sản xuất - Vận hành sản xuất', label: 'Sản xuất - Vận hành sản xuất' },
    { value: 'Vật tư - Thiết bị', label: 'Vật tư - Thiết bị' },
    { value: 'Môi trường - Xử lý chất thải', label: 'Môi trường - Xử lý chất thải' },
    { value: 'KD bất động sản', label: 'KD bất động sản' },
    { value: 'Ô tô - xe máy', label: 'Ô tô - xe máy' },
    { value: 'Nhập liệu', label: 'Nhập liệu' },
    { value: 'Việc làm Tết', label: 'Việc làm Tết' },
    { value: 'Thư ký - Trợ lý', label: 'Thư ký - Trợ lý' },
    { value: 'Đầu bếp - phụ bếp', label: 'Đầu bếp - phụ bếp' },
    { value: 'Bảo hiểm', label: 'Bảo hiểm' },
    { value: 'Làm đẹp - Thể lực - Spa', label: 'Làm đẹp - Thể lực - Spa' },
    { value: 'Công chức - Viên chức', label: 'Công chức - Viên chức' },
    { value: 'Giao thông vận tải - Thủy lợi - Cầu đường', label: 'Giao thông vận tải - Thủy lợi - Cầu đường' },
    { value: 'Bảo trì', label: 'Bảo trì' },
    { value: 'An toàn lao động', label: 'An toàn lao động' },
    { value: 'Mỹ phẩm - Thời trang - Trang sức', label: 'Mỹ phẩm - Thời trang - Trang sức' },
    { value: 'Thương mại điện tử', label: 'Thương mại điện tử' },
    { value: 'Giúp việc', label: 'Giúp việc' },
    { value: 'Bưu chính viễn thông', label: 'Bưu chính viễn thông' },
    { value: 'Nghệ thuật - Điện ảnh', label: 'Nghệ thuật - Điện ảnh' },
    { value: 'Thiết kế web', label: 'Thiết kế web' },
    { value: 'Lương cao', label: 'Lương cao' },
    { value: 'Tài chính', label: 'Tài chính' },
    { value: 'Kỹ thuật ứng dụng', label: 'Kỹ thuật ứng dụng' },
    { value: 'Điện tử viễn thông', label: 'Điện tử viễn thông' },
    { value: 'Công nghệ thực phẩm', label: 'Công nghệ thực phẩm' },
    { value: 'Phát triển thị trường', label: 'Phát triển thị trường' },
    { value: 'Khu chế xuất - Khu công nghiệp', label: 'Khu chế xuất - Khu công nghiệp' },
    { value: 'Tiếp thị - Quảng cáo', label: 'Tiếp thị - Quảng cáo' },
    { value: 'Logistic', label: 'Logistic' },
    { value: 'In ấn - Xuất bản', label: 'In ấn - Xuất bản' },
    { value: 'Thể dục - Thể thao', label: 'Thể dục - Thể thao' },
    { value: 'Dầu khí - Địa chất', label: 'Dầu khí - Địa chất' },
    { value: 'Chăn nuôi - Thú y', label: 'Chăn nuôi - Thú y' },
    { value: 'Quan hệ đối ngoại', label: 'Quan hệ đối ngoại' },
    { value: 'Công nghệ cao', label: 'Công nghệ cao' },
    { value: 'Hoạch định - Dự án', label: 'Hoạch định - Dự án' },
    { value: 'Lễ tân - PG - PB', label: 'Lễ tân - PG - PB' },
    { value: 'Copywriter', label: 'Copywriter' },
    { value: 'Hàng không', label: 'Hàng không' },
    { value: 'Tổ chức sự kiện', label: 'Tổ chức sự kiện' },
    { value: 'Hàng hải', label: 'Hàng hải' },
    { value: 'Truyền thông', label: 'Truyền thông' },
    { value: 'Trắc địa', label: 'Trắc địa' },
    { value: 'Thu ngân', label: 'Thu ngân' },
    { value: 'Telesales', label: 'Telesales' },
    { value: ' Pha chế - Bar', label: ' Pha chế - Bar' },
    { value: 'Thư viện', label: 'Thư viện' },
    { value: 'Thống kê', label: 'Thống kê' },
    { value: 'Quản lý đơn hàng', label: 'Quản lý đơn hàng' },
    { value: 'Startup', label: 'Startup' },
    { value: 'Thủy sản', label: 'Xây' },
    { value: 'Xuất khẩu lao động', label: 'Xuất khẩu lao động' },
    { value: 'Ngành nghề khác', label: 'Ngành nghề khác' },



]

export const listIconStatus:Iicons[] = [
    {
        id: 1,
        img: 'https://timviec365.vn/images/img_comment/Ic_1.png',
        alt: 'Thích',
        style: 'blue',
    },
    {
        id: 2,
        img: 'https://timviec365.vn/images/img_comment/Ic_2.png',
        alt: 'Yêu thích',
        style: 'red',
    },
    {
        id: 3,
        img: 'https://timviec365.vn/images/img_comment/Ic_3.png',
        alt: 'Wow',
        style: 'orange',
    },
    {
        id: 4,
        img: 'https://timviec365.vn/images/img_comment/Ic_4.png',
        alt: 'Thương thương',
        style: 'orange',
    },
    {
        id: 5,
        img: 'https://timviec365.vn/images/img_comment/Ic_5.png',
        alt: 'Phẫn nộ',
        style: 'orange',
    },
    {
        id: 6,
        img: 'https://timviec365.vn/images/img_comment/Ic_6.png',
        alt: 'Buồn',
        style: 'orange',
    },
    {
        id: 7,
        img: 'https://timviec365.vn/images/img_comment/Ic_7.png',
        alt: 'Haha',
        style: 'orange',
    },
]